name: Integration tests

on:
    workflow_call:

jobs:
    integration-tests:
        name: Integration tests
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        container:
            image: swift:6.0-noble
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Mark the workspace as safe
              # https://github.com/actions/checkout/issues/766
              run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

            - name: Install bsdtar
              run: |
                which bsdtar || (apt-get -q update && apt-get -yq install libarchive-tools)

            - name: Run test job
              env:
                  REGISTRY_HOST: registry
                  REGISTRY_PORT: 5000
              run: |
                  swift test

    containertool-resources-test:
        name: Containertool resources test
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Mark the workspace as safe
              # https://github.com/actions/checkout/issues/766
              run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

            - name: Check plugin streaming output is reassembled and printed properly
              run: |
                  scripts/test-containertool-resources.sh

    plugin-streaming-output-test:
        name: Plugin streaming output test
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Mark the workspace as safe
              # https://github.com/actions/checkout/issues/766
              run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

            - name: Check plugin streaming output is reassembled and printed properly
              run: |
                  scripts/test-plugin-output-streaming.sh
