name: main

on:
    push:
        branches:
            - main
    schedule:
        - cron: '12 3 * * *'

jobs:
    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_9_enabled: false
            linux_5_10_enabled: false
            linux_6_0_arguments_override: "--skip SmokeTests"
            linux_nightly_6_1_arguments_override: "--skip SmokeTests"
            linux_nightly_main_arguments_override: "--skip SmokeTests"

    integration-tests:
        name: Integration tests
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        container:
            image: swift:6.0-noble
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Mark the workspace as safe
              # https://github.com/actions/checkout/issues/766
              run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

            - name: Run test job
              env:
                  REGISTRY_HOST: registry
                  REGISTRY_PORT: 5000
              run: |
                  swift test

    endtoend-tests:
        name: End to end tests
        uses: ./.github/workflows/endtoend_tests.yml
