name: main

on:
    push:
        branches:
            - main
    schedule:
        - cron: '12 3 * * *'

jobs:
    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_9_enabled: false
            linux_5_10_enabled: false
            linux_6_0_arguments_override: "--skip SmokeTests"
            linux_nightly_6_1_arguments_override: "--skip SmokeTests"
            linux_nightly_main_arguments_override: "--skip SmokeTests"

    integration-tests:
        name: Integration tests
        uses: ./.github/workflows/integration_tests.yml

    endtoend-tests:
        name: End to end tests
        uses: ./.github/workflows/endtoend_tests.yml
